version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@8.2.1
  mem: circleci/rememborb@0.0.2
  node: circleci/node@5.2.0
  slack: circleci/slack@4.12.6

jobs:
  cas1_e2e_tests:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.2-focal
    parallelism: 4
    circleci_ip_ranges: true # opt-in to jobs running on a restricted set of IPs
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'npm install -g npm@9.8.1'
      - node/install-packages
      - run:
          name: E2E Check
          command: |
            SHARD="$((${CIRCLE_NODE_INDEX}+1))"
            username="HMPPS_AUTH_USERNAME_$SHARD"
            password="HMPPS_AUTH_PASSWORD_$SHARD"
            email="HMPPS_AUTH_EMAIL_$SHARD"
            name="HMPPS_AUTH_NAME_$SHARD"
            HMPPS_AUTH_USERNAME="${!username}"
            HMPPS_AUTH_PASSWORD="${!password}"
            HMPPS_AUTH_EMAIL="${!email}"
            HMPPS_AUTH_NAME="${!name}"
            npm run test -- --shard=${SHARD}/${CIRCLE_NODE_TOTAL}
      - store_artifacts:
          path: playwright-report
          destination: playwright-report
      - store_artifacts:
          path: test-results
          destination: test-results

workflows:
  test:
    jobs:
      - cas1_e2e_tests:
          context:
            - hmpps-community-accommodation
            - approved-premises-ui-e2e
